export const APP_ROLES = {
  REQUESTER: 'requester',
  MANAGER: 'manager',
  PROCUREMENT: 'procurement',
  MD_ASSISTANT: 'md_assistant',
  ACCOUNTING: 'accounting',
  ADMIN: 'admin',
}

export const LEGACY_ROLE_ALIASES = {
  staff: APP_ROLES.REQUESTER,
}

export const APP_ROLE_LIST = [
  APP_ROLES.REQUESTER,
  APP_ROLES.MANAGER,
  APP_ROLES.PROCUREMENT,
  APP_ROLES.MD_ASSISTANT,
  APP_ROLES.ACCOUNTING,
  APP_ROLES.ADMIN,
]

export const ROLE_LABELS = {
  [APP_ROLES.REQUESTER]: 'Requester',
  [APP_ROLES.MANAGER]: 'Manager',
  [APP_ROLES.PROCUREMENT]: 'Procurement',
  [APP_ROLES.MD_ASSISTANT]: 'MD Assistant',
  [APP_ROLES.ACCOUNTING]: 'Accounting',
  [APP_ROLES.ADMIN]: 'Admin',
  staff: 'Requester',
}

export const PR_STATUSES = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  PARTIALLY_CONVERTED_TO_PO: 'partially_converted_to_po',
  CONVERTED_TO_PO: 'converted_to_po',
  CLOSED: 'closed',
}

export const LEGACY_PR_STATUS_ALIASES = {
  pending: PR_STATUSES.SUBMITTED,
}

export const PR_STATUS_LIST = [
  PR_STATUSES.DRAFT,
  PR_STATUSES.SUBMITTED,
  PR_STATUSES.APPROVED,
  PR_STATUSES.REJECTED,
  PR_STATUSES.PARTIALLY_CONVERTED_TO_PO,
  PR_STATUSES.CONVERTED_TO_PO,
  PR_STATUSES.CLOSED,
]

export const PO_STATUSES = {
  DRAFT: 'draft',
  PENDING_VARIANCE_CONFIRMATION: 'pending_variance_confirmation',
  PENDING_FINAL_APPROVAL: 'pending_final_approval',
  APPROVED_FOR_PAYMENT: 'approved_for_payment',
  PENDING_ACCOUNTING_CHECK: 'pending_accounting_check',
  ACCOUNTING_IN_REVIEW: 'accounting_in_review',
  ORDERED: 'ordered',
  PARTIALLY_RECEIVED: 'partially_received',
  FULLY_RECEIVED: 'fully_received',
  CLOSED: 'closed',
  CANCELLED: 'cancelled',
}

export const PO_STATUS_LIST = [
  PO_STATUSES.DRAFT,
  PO_STATUSES.PENDING_VARIANCE_CONFIRMATION,
  PO_STATUSES.PENDING_FINAL_APPROVAL,
  PO_STATUSES.APPROVED_FOR_PAYMENT,
  PO_STATUSES.PENDING_ACCOUNTING_CHECK,
  PO_STATUSES.ACCOUNTING_IN_REVIEW,
  PO_STATUSES.ORDERED,
  PO_STATUSES.PARTIALLY_RECEIVED,
  PO_STATUSES.FULLY_RECEIVED,
  PO_STATUSES.CLOSED,
  PO_STATUSES.CANCELLED,
]

export const APPROVAL_ACTIONS = {
  SUBMIT: 'submit',
  APPROVE: 'approve',
  REJECT: 'reject',
  SEND_BACK: 'send_back',
  CONVERT_TO_PO: 'convert_to_po',
  ACCOUNTING_CHECK: 'accounting_check',
  RECEIVE: 'receive',
  CLOSE: 'close',
  CANCEL: 'cancel',
}

export const APPROVAL_ACTION_LIST = [
  APPROVAL_ACTIONS.SUBMIT,
  APPROVAL_ACTIONS.APPROVE,
  APPROVAL_ACTIONS.REJECT,
  APPROVAL_ACTIONS.SEND_BACK,
  APPROVAL_ACTIONS.CONVERT_TO_PO,
  APPROVAL_ACTIONS.ACCOUNTING_CHECK,
  APPROVAL_ACTIONS.RECEIVE,
  APPROVAL_ACTIONS.CLOSE,
  APPROVAL_ACTIONS.CANCEL,
]

export const WORKFLOW_ACTIONS = {
  CREATE_PR: 'create_pr',
  SUBMIT_PR: 'submit_pr',
  APPROVE_PR: 'approve_pr',
  REJECT_PR: 'reject_pr',
  CREATE_PO_DRAFT: 'create_po_draft',
  CONFIRM_VARIANCE: 'confirm_variance',
  FINAL_APPROVE_PO: 'final_approve_po',
  ACCOUNTING_REVIEW: 'accounting_review',
  RECEIVE_GOODS: 'receive_goods',
  CLOSE_PO: 'close_po',
}

export const WORKFLOW_ACTION_LIST = [
  WORKFLOW_ACTIONS.CREATE_PR,
  WORKFLOW_ACTIONS.SUBMIT_PR,
  WORKFLOW_ACTIONS.APPROVE_PR,
  WORKFLOW_ACTIONS.REJECT_PR,
  WORKFLOW_ACTIONS.CREATE_PO_DRAFT,
  WORKFLOW_ACTIONS.CONFIRM_VARIANCE,
  WORKFLOW_ACTIONS.FINAL_APPROVE_PO,
  WORKFLOW_ACTIONS.ACCOUNTING_REVIEW,
  WORKFLOW_ACTIONS.RECEIVE_GOODS,
  WORKFLOW_ACTIONS.CLOSE_PO,
]

export const WORKFLOW_ACTION_LABELS = {
  [WORKFLOW_ACTIONS.CREATE_PR]: 'Create PR',
  [WORKFLOW_ACTIONS.SUBMIT_PR]: 'Submit PR',
  [WORKFLOW_ACTIONS.APPROVE_PR]: 'Approve PR',
  [WORKFLOW_ACTIONS.REJECT_PR]: 'Reject PR',
  [WORKFLOW_ACTIONS.CREATE_PO_DRAFT]: 'Create PO Draft',
  [WORKFLOW_ACTIONS.CONFIRM_VARIANCE]: 'Confirm Variance',
  [WORKFLOW_ACTIONS.FINAL_APPROVE_PO]: 'Final Approve PO',
  [WORKFLOW_ACTIONS.ACCOUNTING_REVIEW]: 'Accounting Review',
  [WORKFLOW_ACTIONS.RECEIVE_GOODS]: 'Receive Goods',
  [WORKFLOW_ACTIONS.CLOSE_PO]: 'Close PO',
}

export const DOCUMENT_TYPES = {
  PR: 'pr',
  PO: 'po',
}

export const DOCUMENT_TYPE_LIST = [DOCUMENT_TYPES.PR, DOCUMENT_TYPES.PO]
